/**
 * Watch: "PROXe in 60 seconds" video guides. Generated by bconclub/proxe-clips (publish/site.mjs).
 * Shown on /onboarding (playlist + chapters), in this order.
 * Do not edit by hand: re-run the publisher after a new render.
 */
export type WatchChapter = { t: number; title: string; text: string }
export type WatchEpisode = {
  slug: string
  clip: string
  order: number
  title: string
  dek: string
  intro: string[]
  shortVersion: string[]
  promise: string
  duration: number
  video: string
  poster: string
  captions: string
  chapters: WatchChapter[]
  transcript: string[]
}

export const WATCH_EPISODES: WatchEpisode[] = [
  {
    "slug": "watch-what-is-proxe",
    "clip": "00-overview",
    "order": 1,
    "title": "What is PROXe?",
    "dek": "A short tour of the PROXe dashboard. Where leads land, how they get ranked, what a conversation looks like, and where bookings go.",
    "intro": [
      "Start here. This is the PROXe dashboard, recorded on a demo account with a busy month of leads.",
      "You will see where every lead lands, how PROXe decides who is ready to buy, what a conversation looks like, and where bookings end up."
    ],
    "shortVersion": [
      "Every lead lands in one place: WhatsApp, your website, calls and Instagram.",
      "PROXe answers in seconds, scores each lead on what they actually did, and books the slot.",
      "Your team opens the dashboard and knows who to call first, with the story already written."
    ],
    "promise": "You run the business. PROXe runs the follow-up.",
    "duration": 67,
    "video": "/watch/watch-what-is-proxe.mp4",
    "poster": "/watch/watch-what-is-proxe.jpg",
    "captions": "/watch/watch-what-is-proxe.vtt",
    "chapters": [
      {
        "t": 3.3,
        "title": "The problem",
        "text": "Every business that runs ads has the same problem. Leads come in faster than anyone can reply."
      },
      {
        "t": 11.2,
        "title": "What PROXe is",
        "text": "PROXe is your AI front desk for leads. It answers, it scores, it books. Around the clock."
      },
      {
        "t": 19.5,
        "title": "Your business at a glance",
        "text": "This is your business at a glance. Conversations, hot leads, bookings. All live."
      },
      {
        "t": 28.6,
        "title": "Every lead, ranked",
        "text": "Every lead from WhatsApp, your website, calls and Instagram, in one list. Ranked by who's ready to buy."
      },
      {
        "t": 37,
        "title": "The story behind a lead",
        "text": "Open one and the story is already written. What they want, and why they scored ninety."
      },
      {
        "t": 49,
        "title": "Every conversation",
        "text": "Every conversation lives here. PROXe replies in seconds, with buttons that move people forward."
      },
      {
        "t": 56.1,
        "title": "Bookings and reminders",
        "text": "And when someone books, it lands on your calendar. Reminders and all."
      },
      {
        "t": 62,
        "title": "You run the business",
        "text": "You run the business. PROXe runs the follow-up."
      }
    ],
    "transcript": [
      "Every business that runs ads has the same problem. Leads come in faster than anyone can reply.",
      "PROXe is your AI front desk for leads. It answers, it scores, it books. Around the clock.",
      "This is your business at a glance. Conversations, hot leads, bookings. All live.",
      "Every lead from WhatsApp, your website, calls and Instagram, in one list. Ranked by who's ready to buy.",
      "Open one and the story is already written. What they want, and why they scored ninety.",
      "Every conversation lives here. PROXe replies in seconds, with buttons that move people forward.",
      "And when someone books, it lands on your calendar. Reminders and all.",
      "You run the business. PROXe runs the follow-up."
    ]
  },
  {
    "slug": "watch-who-to-call-first",
    "clip": "05-leads",
    "order": 2,
    "title": "Who should I call first?",
    "dek": "Three hundred leads in a week. This is how PROXe decides who you call first, and shows you exactly why.",
    "intro": [
      "Ads work. Then the leads arrive faster than anyone can call them back, and the question becomes who to call first.",
      "PROXe ranks every lead by what they actually did, so the ones ready to buy are always at the top. This video shows the ranking, the score behind it, and the story inside each lead."
    ],
    "shortVersion": [
      "The Priority Lead Queue on the Overview shows who needs a call now.",
      "Each lead gets a score from real behaviour: replies, questions about price, bookings, calls.",
      "Open any lead to see the summary, why they scored what they did, and every message and call in order."
    ],
    "promise": "Every lead ranked. The right one called first.",
    "duration": 51,
    "video": "/watch/watch-who-to-call-first.mp4",
    "poster": "/watch/watch-who-to-call-first.jpg",
    "captions": "/watch/watch-who-to-call-first.vtt",
    "chapters": [
      {
        "t": 3.3,
        "title": "Leads pour in",
        "text": "Say you run a lot of ads. Leads pour in. Three hundred, just this week."
      },
      {
        "t": 10.5,
        "title": "Who do you call first?",
        "text": "So who do you call first? Honestly, it depends on how your sales run."
      },
      {
        "t": 16.4,
        "title": "Already ranked",
        "text": "PROXe already did that thinking. The ones ready to buy sit right at the top."
      },
      {
        "t": 21.4,
        "title": "One list, every channel",
        "text": "Every lead, from every channel, in one list."
      },
      {
        "t": 26.7,
        "title": "A score from what they did",
        "text": "Each one scored on what they actually did. Replied. Asked the price. Booked a call."
      },
      {
        "t": 33.2,
        "title": "The story is written",
        "text": "Open any lead. The story's already written."
      },
      {
        "t": 36.6,
        "title": "Why they scored ninety",
        "text": "See exactly why they scored ninety."
      },
      {
        "t": 40.4,
        "title": "Every message, every call",
        "text": "Every message. Every call."
      },
      {
        "t": 44.1,
        "title": "Call the right person first",
        "text": "So you stop digging, and call the right person first."
      }
    ],
    "transcript": [
      "Say you run a lot of ads. Leads pour in. Three hundred, just this week.",
      "So who do you call first? Honestly, it depends on how your sales run.",
      "PROXe already did that thinking. The ones ready to buy sit right at the top.",
      "Every lead, from every channel, in one list.",
      "Each one scored on what they actually did. Replied. Asked the price. Booked a call.",
      "Open any lead. The story's already written.",
      "See exactly why they scored ninety.",
      "Every message. Every call.",
      "So you stop digging, and call the right person first."
    ]
  },
  {
    "slug": "watch-all-your-conversations",
    "clip": "06-inbox",
    "order": 3,
    "title": "Where are all my conversations?",
    "dek": "WhatsApp, Instagram and your website, all in one inbox. Open any chat and the whole story is already there.",
    "intro": [
      "Your customers talk to you on WhatsApp, Instagram and your website. PROXe puts every one of those conversations in one inbox.",
      "This video shows the inbox, how to filter by channel, and what you see when you open a chat."
    ],
    "shortVersion": [
      "Every conversation from every channel, newest on top.",
      "Filter to just WhatsApp or just Instagram in one tap.",
      "Open a chat to see the full thread, the lead's score and their owner. Reply yourself any time and PROXe steps aside."
    ],
    "promise": "Every chat, every channel. One inbox.",
    "duration": 37,
    "video": "/watch/watch-all-your-conversations.mp4",
    "poster": "/watch/watch-all-your-conversations.jpg",
    "captions": "/watch/watch-all-your-conversations.vtt",
    "chapters": [
      {
        "t": 2.9,
        "title": "Where customers talk",
        "text": "Where do your customers talk to you? WhatsApp. Instagram. Your website."
      },
      {
        "t": 9.4,
        "title": "Three apps, lost chats",
        "text": "That's three apps, and a few chats that slip away."
      },
      {
        "t": 13.9,
        "title": "One inbox",
        "text": "In PROXe, it all lands in one inbox."
      },
      {
        "t": 17,
        "title": "Filter by channel",
        "text": "Just WhatsApp? One tap. Just Instagram? One tap."
      },
      {
        "t": 22.8,
        "title": "The whole story",
        "text": "Open a chat and the whole story is there, even the buttons they tapped."
      },
      {
        "t": 27.2,
        "title": "Who they are",
        "text": "Plus who they are, and who on your team owns them."
      },
      {
        "t": 31.5,
        "title": "Jump in anytime",
        "text": "Jump in anytime. PROXe steps aside. One place, full context."
      }
    ],
    "transcript": [
      "Where do your customers talk to you? WhatsApp. Instagram. Your website.",
      "That's three apps, and a few chats that slip away.",
      "In PROXe, it all lands in one inbox.",
      "Just WhatsApp? One tap. Just Instagram? One tap.",
      "Open a chat and the whole story is there, even the buttons they tapped.",
      "Plus who they are, and who on your team owns them.",
      "Jump in anytime. PROXe steps aside. One place, full context."
    ]
  },
  {
    "slug": "watch-whos-coming-this-week",
    "clip": "08-bookings",
    "order": 4,
    "title": "Who's coming in this week?",
    "dek": "Every demo, visit and follow-up on one calendar, with reminders that go out on their own.",
    "intro": [
      "When a lead books on WhatsApp or on a call, PROXe puts it on your calendar and sends the reminders.",
      "This video shows the week at a glance, what is inside an event, and today's queue."
    ],
    "shortVersion": [
      "Every booking, follow-up and AI suggestion on one calendar.",
      "Tap an event to see who, when, and the note your team left.",
      "Reminders go out a day before and thirty minutes before, automatically."
    ],
    "promise": "Fewer no-shows. Nobody forgotten.",
    "duration": 37,
    "video": "/watch/watch-whos-coming-this-week.mp4",
    "poster": "/watch/watch-whos-coming-this-week.jpg",
    "captions": "/watch/watch-whos-coming-this-week.vtt",
    "chapters": [
      {
        "t": 2.9,
        "title": "Who's coming in?",
        "text": "Who's coming in this week? And who needs a nudge?"
      },
      {
        "t": 8.5,
        "title": "One calendar",
        "text": "PROXe knows. Every demo, every visit, one calendar."
      },
      {
        "t": 15,
        "title": "Bookings land here",
        "text": "Someone books on WhatsApp? It just shows up here."
      },
      {
        "t": 18.4,
        "title": "Inside an event",
        "text": "Tap it: who, when, and your team's note."
      },
      {
        "t": 22.9,
        "title": "Today's queue",
        "text": "Today's queue? Right down the side."
      },
      {
        "t": 25.4,
        "title": "Automatic reminders",
        "text": "Reminders go out a day before and thirty minutes before. Automatically."
      },
      {
        "t": 31.8,
        "title": "Fewer no-shows",
        "text": "Fewer no-shows. Nobody forgotten."
      }
    ],
    "transcript": [
      "Who's coming in this week? And who needs a nudge?",
      "PROXe knows. Every demo, every visit, one calendar.",
      "Someone books on WhatsApp? It just shows up here.",
      "Tap it: who, when, and your team's note.",
      "Today's queue? Right down the side.",
      "Reminders go out a day before and thirty minutes before. Automatically.",
      "Fewer no-shows. Nobody forgotten."
    ]
  },
  {
    "slug": "watch-message-hundreds-at-once",
    "clip": "11-campaigns",
    "order": 10,
    "title": "Message hundreds of leads at once",
    "dek": "Describe who should get an offer, pick an approved WhatsApp message, and every reply comes back to Chats.",
    "intro": [
      "Campaigns send one approved WhatsApp message to the right group of leads.",
      "This video shows choosing an audience in plain words, picking a message, and where replies go."
    ],
    "shortVersion": [
      "Describe the audience in plain words; PROXe finds the matching leads.",
      "Choose an approved WhatsApp template and when it goes out.",
      "Every reply lands back in Chats, with the lead's history."
    ],
    "promise": "One offer. The right people.",
    "duration": 31,
    "video": "/watch/watch-message-hundreds-at-once.mp4",
    "poster": "/watch/watch-message-hundreds-at-once.jpg",
    "captions": "/watch/watch-message-hundreds-at-once.vtt",
    "chapters": [
      {
        "t": 2.9,
        "title": "A new offer",
        "text": "Got a new offer? Hundreds of people should hear about it."
      },
      {
        "t": 7.3,
        "title": "Pick the audience",
        "text": "Describe who should get it in plain words. PROXe finds them."
      },
      {
        "t": 16.7,
        "title": "Pick the message",
        "text": "Pick an approved WhatsApp message and set when it goes out."
      },
      {
        "t": 21.9,
        "title": "Replies come back",
        "text": "Every reply comes straight back into Chats."
      },
      {
        "t": 25.8,
        "title": "One minute",
        "text": "One offer. The right people. One minute."
      }
    ],
    "transcript": [
      "Got a new offer? Hundreds of people should hear about it.",
      "Describe who should get it in plain words. PROXe finds them.",
      "Pick an approved WhatsApp message and set when it goes out.",
      "Every reply comes straight back into Chats.",
      "One offer. The right people. One minute."
    ]
  },
  {
    "slug": "watch-get-alerted",
    "clip": "14-alerts",
    "order": 11,
    "title": "Get alerted when it matters",
    "dek": "PROXe pings you the moment a lead turns hot, books a slot, or asks to talk to a person.",
    "intro": [
      "You do not need to watch the dashboard all day. PROXe tells you when something needs you.",
      "This video shows the notifications and what triggers them."
    ],
    "shortVersion": [
      "Alerts when a lead turns hot, books, or asks for a human.",
      "New leads and new messages show in one place.",
      "Choose which alerts you get in settings."
    ],
    "promise": "You hear about it the moment it matters.",
    "duration": 29,
    "video": "/watch/watch-get-alerted.mp4",
    "poster": "/watch/watch-get-alerted.jpg",
    "captions": "/watch/watch-get-alerted.vtt",
    "chapters": [
      {
        "t": 2.9,
        "title": "A hot lead is waiting",
        "text": "A hot lead is waiting right now. Do you know?"
      },
      {
        "t": 8.7,
        "title": "The moment it happens",
        "text": "PROXe tells you the moment a lead turns hot, books, or asks for a person."
      },
      {
        "t": 24.1,
        "title": "When it matters",
        "text": "You hear about it the moment it matters."
      }
    ],
    "transcript": [
      "A hot lead is waiting right now. Do you know?",
      "PROXe tells you the moment a lead turns hot, books, or asks for a person.",
      "You hear about it the moment it matters."
    ]
  }
]

export const getWatchEpisode = (slug: string) => WATCH_EPISODES.find((e) => e.slug === slug)
export const getNextEpisode = (slug: string) => {
  const i = WATCH_EPISODES.findIndex((e) => e.slug === slug)
  return i >= 0 ? WATCH_EPISODES[i + 1] : undefined
}
