const fs=require('fs'),vm=require('vm'),ts=require('typescript'),assert=require('node:assert/strict'),crypto=require('node:crypto');
function load(file,mocks={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,require:n=>{if(n in mocks)return mocks[n];throw Error('Unexpected import '+n)},Response,Request,URL,AbortSignal,Buffer,Date,console,process:{env:{}},...globals});return exports;}
const env={ELEVENLABS_API_KEY:'test',DIAL_API_KEY:'dial',ARC_INGEST_SECRET:'arc',ELEVENLABS_WEBHOOK_SECRET:'sign',PROXE_INTENT_BASE:'https://proxe.invalid',PROXE_INBOUND_API_KEY:'key'};
const policy=load('app/lib/outreachPolicy.ts');let count=0;async function check(name,fn){await fn();console.log('PASS '+name);count++;}
const N={NextResponse:Response};
(async()=>{
 await check('silence placeholders are not speech',()=>assert.equal(policy.meaningfulSpeech('... …'),false));
 await check('IVR completed is no answer, never qualified',()=>{const r=policy.callEvidence({status:'done',transcript:[{role:'user',message:'Press one for reception'}]});assert.equal(r.outcome,'no_answer');assert.equal(r.qualified,false)});
 await check('callback preferred time is retained for review',()=>assert.equal(policy.callEvidence({status:'done',transcript:[{role:'user',message:'5:30 you can call'}]}).outcome,'callback'));
 await check('normal conversation is not automatically qualified',()=>assert.equal(policy.callEvidence({status:'done',transcript:[{role:'user',message:'Okay tell me'}]}).outcome,'connected'));
 for(const agent of ['agent_9901m0sn70f1ejn84enhccrns2kt','agent_8901m0sn6y14eegsqh7mmgdswm92','agent_1201m0sn71mvf3arwzfwv4h9s2v1','agent_0301m0na3jjdfkta2sza4h317m4d','unknown']) await check('send guard blocks '+agent,async()=>{let urls=[];const route=load('app/api/agent/send-oncall-wa/route.ts',{'next/server':N,'node:crypto':crypto,'../../../lib/outreachPolicy':policy,'../../../lib/oncallWhatsAppSent':{oncallWhatsAppSent:new Map()}},{process:{env},fetch:async u=>{urls.push(u);return Response.json({agent_id:agent})}});const r=await route.POST(new Request('https://bdr.test',{method:'POST',body:JSON.stringify({phone:'+919999999999',conversation_id:'conv_test'})}));assert(r.status>=400);assert.equal(urls.length,1);assert(!urls.some(u=>u.includes('proxe.invalid')))});
 await check('provider unavailable fails closed before send',async()=>{const r=load('app/api/agent/send-oncall-wa/route.ts',{'next/server':N,'node:crypto':crypto,'../../../lib/outreachPolicy':policy,'../../../lib/oncallWhatsAppSent':{oncallWhatsAppSent:new Map()}},{process:{env},fetch:async()=>{throw Error('down')}});assert.equal((await r.POST(new Request('https://bdr.test',{method:'POST',body:JSON.stringify({phone:'9999999999',conversation_id:'conv_test'})}))).status,503)});
 for(const status of [200,404,503]) await check('outbound webhook stays ARC with ingest '+status,async()=>{const urls=[];const route=load('app/api/webhooks/elevenlabs/route.ts',{'next/server':N,'node:crypto':crypto,'../../../lib/outreachPolicy':policy,'../../../lib/oncallWhatsAppSent':{oncallWhatsAppSent:new Map()},'../../../lib/leadsSupabase':{recordCallTranscript:()=>{throw Error('PROXe write attempted')}}},{process:{env},fetch:async u=>{urls.push(u);return Response.json({ok:status===200},{status})}});const raw=JSON.stringify({type:'post_call_transcription',data:{agent_id:'agent_9901m0sn70f1ejn84enhccrns2kt',conversation_id:'conv_test',status:'done',metadata:{phone_call:{external_number:'+919999999999'}},transcript:[{role:'user',message:'...'}]}}),t=String(Math.floor(Date.now()/1000)),sig=crypto.createHmac('sha256','sign').update(t+'.'+raw).digest('hex');const r=await route.POST(new Request('https://bdr.test',{method:'POST',headers:{'elevenlabs-signature':'t='+t+',v0='+sig},body:raw}));assert.equal(r.status,status===200?200:500);assert.equal(urls.length,1);assert(urls[0].includes('arc.bconclub.com'))});
 for(const reserveStatus of [200,409,503]) await check('dry run checks ARC and never dials '+reserveStatus,async()=>{const urls=[];const route=load('app/api/outreach-dial/route.ts',{'next/server':N,'../../lib/quietHours':{isQuiet:()=>false,nextOpenTime:()=>new Date()}},{process:{env},fetch:async u=>{urls.push(u);return Response.json({target_id:'test-target'},{status:reserveStatus})}});const r=await route.POST(new Request('https://bdr.test',{method:'POST',headers:{authorization:'Bearer dial'},body:JSON.stringify({phone:'9999999999',agent:'dm',vars:{business_name:'Clinic',first_name:'there'},dry_run:true})}));assert.equal(urls.length,1);assert(urls[0].includes('/reserve'));if(reserveStatus===200){assert.equal((await r.json()).agent,'noname')}else assert(r.status>=400)});
 console.log(count+' call control checks passed');
})().catch(e=>{console.error(e);process.exitCode=1});
